# This file was generated by the {rix} R package v0.18.2 on 2026-04-09
# with following call:
# >rix(r_ver = "6139e248216c35fb431cde479298552fec2a8437",
#  > r_pkgs = c("devtools",
#  > "dplyr",
#  > "ggExtra",
#  > "ggplot2",
#  > "ggsci",
#  > "mia",
#  > "miaViz",
#  > "targets",
#  > "tarchetypes",
#  > "mikropml",
#  > "ranger",
#  > "patchwork",
#  > "quarto",
#  > "rix",
#  > "scater",
#  > "stringr",
#  > "tidyr",
#  > "purrr",
#  > "crew",
#  > "usethis"),
#  > system_pkgs = c("quarto"),
#  > git_pkgs = NULL,
#  > ide = "code",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses upstream nixpkgs' revision 6139e248216c35fb431cde479298552fec2a8437 for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/6139e248216c35fb431cde479298552fec2a8437.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      crew
      devtools
      dplyr
      ggExtra
      ggplot2
      ggsci
      languageserver
      mia
      miaViz
      mikropml
      patchwork
      purrr
      quarto
      ranger
      rix
      scater
      stringr
      tarchetypes
      targets
      tidyr
      usethis;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      quarto
      R
      vscode
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
